title: My Collection
description: My Collection
baseurl: "/Collection"
url: "https://RomanNiukalo.github.io"

remote_theme: pages-themes/cayman
markdown: kramdown

include:
  - _data
  - assets

plugins:
  - jekyll-feed
  - jekyll-remote-theme
