title: Our Collection
description: Our Collection
baseurl: "/Collection"
url: "https://RomanNiukalo.github.io"

markdown: kramdown
theme: jekyll-theme-cayman

include:
  - _data
  - assets

plugins:
  - jekyll-feed