title: My Collection
description: My Collection
baseurl: "/Collection"
url: "https://RomanNiukalo.github.io"

remote_theme: pages-themes/cayman@v0.2.0
markdown: kramdown

include:
  - _data
  - assets

plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  coins:
    output: true
    permalink: /coins/:name/